services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/html:/usr/share/nginx/html
    ports:
      - 80:80
  mysql:
    image: mysql/mysql-server
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${mysql_pass}
    volumes:
      - ./docker/mysql:/var/lib/mysql
    ports:
      - 3306:3306
  redis:
    image: redis
    container_name: redis
    volumes:
      - ./docker/redis:/data
    ports:
      - 6379:6379
  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - ./docker/mongo:/data
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${mongo_pass}
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${mongo_pass}
      ME_CONFIG_MONGODB_URL: mongodb://root:${mongo_pass}@mongo:27017/
    depends_on:
      - mongo
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
    depends_on:
      - zookeeper
