scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ '192.168.0.109:9090' ]
  - job_name: 'web'
    scrape_interval: 5s
    static_configs:
      - targets: [ '192.168.0.109:8089' ]
rule_files:
  - /opt/bitnami/prometheus/conf/rule.yml
alerting:
  alertmanagers:
    - static_configs:
        - targets: [ 'alertmanager:9093' ]
